name: remote
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  retrofit: ^4.0.1
  analyzer: ^5.7.1
  dio: ^5.0.1
  json_serializable: ^6.6.1
  rxdart: ^0.27.7





  repository:
    path: ../repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3