name: viewModel
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  usecase:
    path: ../usecase

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0